### ISSUE TITLE
Make performance.mark to take a FetchEvent instead of adding performanceMark on FetchEvent

### ISSUE THREAD

**Issue by rniwa** [wanderview/fetchevent-worker-timing#2]
Instead of adding an interface specific to adding a performance entry related information to `FetchEvent` as [currently proposed](https://github.com/wanderview/fetchevent-worker-timing/blob/master/explainer.md), add a FetchEvent as an optional argument to `performance.mark`. 

This would avoid duplicating a very similar logic in two different places and avoids the layering violation of `FetchEvent` being aware of performance API.

This will allow the passing of meta data and other API benefits currently being proposed as well as future improvements for `performance.mark` to automatically benefit service workers.

**Comment by wanderview** [comment]
Thanks for the feedback.  I've been thinking about this since the meeting and I think removing the method from `FetchEvent` makes a lot of sense.

At lunch @toddreifsteck further suggested maybe allowing the entry to be passed to a method on `FetchEvent` instead of explicitly tightly coupling the APIs.  So, in User Timing L3 where `performance.mark()` returns its entry we could do something like this:

```javascript
self.addEventListener("fetch", evt => {
  let entry = performance.mark("foo");
  evt.addTimingEntry(entry);
});
```

This would have a couple of nice benefits.

1. As with your suggestion it would allow any changes to User Timing API to automatically benefit the service worker case.
2. It opens the possibility to associate other entry types with the `FetchEvent` in the future.  For example, maybe we want to allow the script to associate nested `PerformanceResourceTiming` entries from the service worker context for `fetch()` calls it makes.  (I'm not proposing to do this right now, but its nice to have the API flexibility to support it.)

I'm going to plan to incorporate some change like this in the proposal this week.  Thanks again.
